### ISSUE TITLE
WARNING Wrong value for 'loglevel' in 'Definition'. Using default one: ''INFO'' in Fail2ban 0.9.0 with Fedora 20

### ISSUE THREAD

**Issue by skasai** [fail2ban/fail2ban#1063]
This bug has returned...  Installed on Fedora 20 running iptables, when starting up:

WARNING Wrong value for 'loglevel' in 'Definition'. Using default one: ''INFO''

Specified in the fail2ban.conf is:
<pre>
# Option: loglevel
# Notes.: Set the log level output.
#         CRITICAL
#         ERROR
#         WARNING
#         NOTICE
#         INFO
#         DEBUG
# Values: [ LEVEL ]  Default: ERROR
#
loglevel = NOTICE
</pre>

**Comment by leeclemens** [comment]
Are you referencing https://github.com/fail2ban/fail2ban/issues/657?

**Comment by skasai** [comment]
It looks like that is the same issue, however, it also shows it is closed, but seems like it has not been resolved or showing how to fix it so that by default, log level is at NOTICE or what value to put in.

**Comment by yarikoptic** [comment]
yes 
 fixed while back
 upgrade

**Comment by skasai** [comment]
Ok...  Here is what I see:

fail2ban.noarch                          0.9-2.fc20                  @updates

This is the latest version I have on the box.

However, looking into messages and restarting the service, even after doing a yum reinstall fail2ban...  The following is shown:
Jun  5 15:19:47 <system> systemd: Started PackageKit Daemon.
Jun  5 15:19:58 <system> systemd: Starting Fail2ban Service...
Jun  5 15:19:58 <system> fail2ban-client: WARNING Wrong value for 'loglevel' in 'Definition'. Using default one: ''INFO''
Jun  5 15:19:58 <system> fail2ban-client: 2015-06-05 15:19:58,861 fail2ban.server.server[15861]: INFO    Starting Fail2ban v0.9.0
Jun  5 15:19:58 <system> fail2ban-client: 2015-06-05 15:19:58,861 fail2ban.server.server[15861]: INFO    Starting in daemon mode
Jun  5 15:19:59 <system> systemd: Started Fail2ban Service.

Note - It says Starting Fail2ban v0.9.0...  

The RPM shows the following information:

Name        : fail2ban
Version     : 0.9
Release     : 2.fc20
Architecture: noarch
Install Date: Fri 05 Jun 2015 03:18:13 PM PDT
Group       : Unspecified
Size        : 1261672
License     : GPLv2+
Signature   : RSA/SHA256, Thu 15 May 2014 06:01:58 PM PDT, Key ID 2eb161fa246110c1
Source RPM  : fail2ban-0.9-2.fc20.src.rpm
Build Date  : Wed 19 Mar 2014 08:17:30 AM PDT
Build Host  : arm02-builder09.arm.fedoraproject.org
Relocations : (not relocatable)
Packager    : Fedora Project
Vendor      : Fedora Project
URL         : http://fail2ban.sourceforge.net/
Summary     : Ban IPs that make too many password failures
Description :
Fail2ban scans log files like /var/log/pwdfail or
/var/log/apache/error_log and bans IP that makes too many password
failures. It updates firewall rules to reject the IP address.

To use the hostsdeny and shorewall actions you must install tcp_wrappers
and shorewall respectively.

This is coming from the Fedora Updates repo...

**Comment by skasai** [comment]
Also, mind you...  I don't have this issue on a CentOS 6.6 box...  So at the moment, I suspect the RPM for Fedora 20 seems either not the correct one from the updates or something else is still missing.

Using fail2ban-client set logelevel notice will work.  But the actual fail2ban.conf or fail2ban.local parsing seems to be still broken.
