### ISSUE TITLE
mysqld-auth.conf not compatible with mysql 5.7.11

### ISSUE THREAD

**Issue by GitzJoey** [fail2ban/fail2ban#1332]
### Environment:

Fedora 23 Server Edition, Fail2Ban installed via OS

### The issue:

it seems that mysqld-auth conf regex is not compatible with the mysql 5.7.11 error log

log sample

> 2016-02-24T15:26:18.237955Z 6 [Note] Access denied for user 'root'@'localhost' (using password: YES)
as noticed:
1. separator between date time using "T"
2. there's leading numeric after time
3. using [Note] instead of [Warning]

#### Steps to reproduce
1. enabled the mysqld-auth filter
2. emulate fail login in mysql
3. fail2ban-client status mysqld-auth not adding any ip address

#### Expected behavior
fail2ban should add new ip address

**Comment by sebres** [comment]
@GitzJoey fixed in #1333: testing is welcome

**Comment by GitzJoey** [comment]
tested and seems ok now, cant wait to ban those nasty ips

**Comment by sebres** [comment]
BTW: if you not really need to access mysql from outside, the more secure way would be to forbid it completely (via firewall) or configure mysql to listen locally only (like `bind-address = 127.0.0.1`)
Or if you know all the connector-hosts, another way would be to allow connecting to the mysql-port for this dedicated IP-addresses only (as well via firewall or mysql-privileges).

**Comment by GitzJoey** [comment]
hi, 
its seem still failing for this particular ip 

> 2016-02-25T12:27:48.767392Z` 10 [Warning] IP address '61.147.82.8' could not be resolved: Name or service not known
2016-02-25T12:27:49.020704Z 10 [Note] Access denied for user 'root'@'61.147.82.8' (using password: YES)
fyi, this ip hitting my server 12 times while my maxretry is 4. I need to open the mysqld port since i working remotely with dynamic ip
thanks

**Comment by GitzJoey** [comment]
here's the fail2ban-regex

[root@fedora gitzjoey]# fail2ban-regex /var/log/mysqld.log /etc/fail2ban/filter.d/mysqld-auth.conf

Running tests
=============

Use   failregex filter file : mysqld-auth, basedir: /etc/fail2ban
Use         log file : /var/log/mysqld.log
Use         encoding : UTF-8


Results
=======

Failregex: 13 total
|-  #) [# of hits] regular expression
|   1) [13] ^\s*(<[^.]+\.[^.]+>)?\s*(?:\S+ )?(?:kernel: \[ *\d+\.\d+\] )?(?:@vserver_\S+ )?(?:(?:\[\d+\])?:\s+[\[\(]?mysqld(?:\(\S+\))?[\]\)]?:?|[\[\(]?mysqld(?:\(\S+\))?[\]\)]?:?(?:\[\d+\])?:?)?\s(?:\[ID \d+ \S+\])?\s*(?:\d+ |\d{6} \s?\d{1,2}:\d{2}:\d{2} )?\[\w+\] Access denied for user '[^']+'@'<HOST>'
`-

Ignoreregex: 0 total

Date template hits:
|- [# of hits] date format
|  [14] Year-Month-Day[T ]24hour:Minute:Second(?:\.Microseconds)?(?:Zone offset)?
`-

Lines: 14 lines, 0 ignored, 13 matched, 1 missed [processed in 0.00 sec]
|- Missed line(s):
|  2016-02-25T12:27:48.767392Z 10 [Warning] IP address '61.147.82.8' could not be resolved: Name or service not known
`-
[root@fedora gitzjoey]#

**Comment by sebres** [comment]
Has you reloaded or restarted fail2ban after changing of the filter? for example `?sudo? fail2ban-client reload`.
Or is this time `2016-02-25T12:27:49` (or at least 4 log entries you mean with the last time of it) was later as `restart time - findtime`, that was specified for your jail? Because the fail2ban-regex in the opposite to fail2ban-server does not taken into account the time of failure.

Normally all new failures (that will be found with fail2ban-regex) will be counted and banned after reaching of `maxretry` **within time specified by findtime**.

**Comment by GitzJoey** [comment]
yes i'm sure i've restarted
the maxretry is 5 and findtime = 600
here's the full log

> 2016-02-25T12:27:48.767392Z 10 [Warning] IP address '61.147.82.8' could not be resolved: Name or service not known
2016-02-25T12:27:49.020704Z 10 [Note] Access denied for user 'root'@'61.147.82.8' (using password: YES)
2016-02-25T12:27:49.878115Z 11 [Note] Access denied for user 'root'@'61.147.82.8' (using password: YES)
2016-02-25T12:27:50.764446Z 12 [Note] Access denied for user 'root'@'61.147.82.8' (using password: YES)
2016-02-25T12:27:51.798530Z 13 [Note] Access denied for user 'root'@'61.147.82.8' (using password: YES)
2016-02-25T12:27:52.636730Z 14 [Note] Access denied for user 'root'@'61.147.82.8' (using password: YES)
2016-02-25T12:27:53.528699Z 15 [Note] Access denied for user 'root'@'61.147.82.8' (using password: YES)
2016-02-25T12:27:55.150192Z 16 [Note] Access denied for user 'root'@'61.147.82.8' (using password: YES)
2016-02-25T12:27:58.057936Z 17 [Note] Access denied for user 'root'@'61.147.82.8' (using password: YES)
2016-02-25T12:27:59.014065Z 18 [Note] Access denied for user 'root'@'61.147.82.8' (using password: YES)
2016-02-25T12:27:59.781714Z 19 [Note] Access denied for user 'root'@'61.147.82.8' (using password: YES)
2016-02-25T12:28:00.645264Z 20 [Note] Access denied for user 'root'@'61.147.82.8' (using password: YES)
2016-02-25T12:28:01.581767Z 21 [Note] Access denied for user 'root'@'61.147.82.8' (using password: YES)
2016-02-25T12:28:03.418483Z 22 [Note] Access denied for user 'root'@'61.147.82.8' (using password: YES)

**Comment by sebres** [comment]
Hmm, I don't know - it is as I wrote, so should be banned if you have restarted before 12:17.
BTW you should see in the fail2ban.log the restart resp. reload of jail.

**Comment by GitzJoey** [comment]
fail2ban-client reload mysqld-auth result 
i dont know does "backend" setting affecting the jail?

> 2016-02-29 00:28:38,702 fail2ban.jail           [1006]: INFO    Jail 'mysqld-auth' stopped
2016-02-29 00:28:38,707 fail2ban.server         [1006]: INFO    Changed logging target to /var/log/fail2ban.log for Fail2ban v0.9.3
2016-02-29 00:28:38,708 fail2ban.jail           [1006]: INFO    Creating new jail 'mysqld-auth'
2016-02-29 00:28:38,708 fail2ban.jail           [1006]: INFO    Jail 'mysqld-auth' uses systemd
2016-02-29 00:28:38,710 fail2ban.jail           [1006]: INFO    Initiated 'systemd' backend
2016-02-29 00:28:38,713 fail2ban.filter         [1006]: INFO    Set maxRetry = 5
2016-02-29 00:28:38,714 fail2ban.actions        [1006]: INFO    Set banTime = 86400
2016-02-29 00:28:38,714 fail2ban.filter         [1006]: INFO    Set findtime = 600
2016-02-29 00:28:38,728 fail2ban.filtersystemd  [1006]: NOTICE  Jail started without 'journalmatch' set. Jail regexs will be checked against all journal entries, which is not advised for performance reasons.
2016-02-29 00:28:38,729 fail2ban.jail           [1006]: INFO    Jail 'mysqld-auth' started
2016-02-29 00:40:04,618 fail2ban.jail           [1006]: INFO    Jail 'mysqld-auth' stopped
2016-02-29 00:40:04,626 fail2ban.server         [1006]: INFO    Changed logging target to /var/log/fail2ban.log for Fail2ban v0.9.3
2016-02-29 00:40:04,627 fail2ban.jail           [1006]: INFO    Creating new jail 'mysqld-auth'
2016-02-29 00:40:04,628 fail2ban.jail           [1006]: INFO    Jail 'mysqld-auth' uses systemd
2016-02-29 00:40:04,629 fail2ban.jail           [1006]: INFO    Initiated 'systemd' backend
2016-02-29 00:40:04,635 fail2ban.filter         [1006]: INFO    Set maxRetry = 5
2016-02-29 00:40:04,636 fail2ban.actions        [1006]: INFO    Set banTime = 86400
2016-02-29 00:40:04,637 fail2ban.filter         [1006]: INFO    Set findtime = 600
2016-02-29 00:40:04,650 fail2ban.filtersystemd  [1006]: NOTICE  Jail started without 'journalmatch' set. Jail regexs will be checked against all journal entries, which is not advised for performance reasons.
2016-02-29 00:40:04,651 fail2ban.jail           [1006]: INFO    Jail 'mysqld-auth' started

**Comment by sebres** [comment]
And?
Restart occurred "29 Feb", failures in "25 Feb"...
What do you want to say?

**Comment by GitzJoey** [comment]
sorry maybe i post a bad example
what i'm  trying to say is, even thou the fail2ban already restarted with the new regex for mysqld-auth
it still not banning the offender. this is my tries today (i'm using mysql workbench 6.3 to test the connection by creating new connection using bad password)

**Comment by sebres** [comment]
Magic happens here :) 

Well, I think your jail does not get any failure of mysqld at all. May've many reasons:
- whatsoever still the old regexp expression will be used, (check via `fail2ban-client -d | grep "mysqld-auth.*regex"`, it uses really new expression);
- mysqld does not provide logging via systemd (rsyslog?, etc.);
- or systemd backend does not get the log entries of mysqld (try `polling` or `pyinotify` and specify correct logpath)

**Comment by GitzJoey** [comment]
hi sebres,
just to inform you that its working now after changing backend to auto
BIG THANKS for your help and support.

thanks
