### ISSUE TITLE
logpath issue: move logic "collecting of logfiles" from client to server resp. filter ...

### ISSUE THREAD

**Issue by sebres** [fail2ban/fail2ban#1379]
Just a reminder for me (will too long provide a PR for this, waiting for 716-cs ... and #1346).

Should fix imho great problem with "collecting of logfiles" client side: current solution uses fixedly list of the log files, found by the moment of the fail2ban starting. 
Variable logfiles of some services (multiple domains, etc.) will not be taken into account, as long as not restart of the fail2ban.
- [X] move logic "collecting of logfiles" from client to server resp. filter ... (* pro rata realized in my own branch);
- [ ] support appearing of new log files (matched) - (for example search in X minutes for new log files, or via pyinotify callback, if supported);
- [ ] better support disappearing of the log files (log-rotate, service down, etc...), and reactivating of jail from idle if log files found again;
- [ ] add `logregex` as additionally extended "replacement" for `logpath`;
- [ ] add `logregex-ignore` (and `logpath-ignore`) for negative filter;

**Comment by sebres** [comment]
should resolve #1407

**Comment by sebres** [comment]
Several issues refer to `Have not found any log file`, in relation to "prevent to start fail2ban service" are partially fixed in #1622

**Comment by eadthem** [comment]
What version was this merged in?  Specificity the 1407 (Related to log files having dates in the name).

Thanks
Eadthem

**Comment by sebres** [comment]
> What version was this merged in?

Nowhere. It's an issue. I should still finish it. Just persistently no time...
And it is a pre-requirement for 1407, that as you can see is still open also.

**Comment by szepeviktor** [comment]
@sebres Should Fail2ban accept multiline logpaths?

```ini
logpath  = %(apache_error_log)s
           /home/*/website/log/*error.log
```

**Comment by sebres** [comment]
Fail2ban self does it... it looks rather as an issue of ConfigReader's and/or ExtractOptions (by supplying to the action "sendmail-geoip-lines").
Currently I don't know which versions are affected (0.9 is too old, so it could be fixed in-between).

The alternative for you which could work - switch to another action (e. g. that using `<matches>` info instead of the log-files).

**Comment by szepeviktor** [comment]
Thank you.

**Comment by sebres** [comment]
yw

> using `<matches>` info instead of the log-files

Oh, forgotten that we had a grave issue with not proper "escaped" `<matches>` - #1726 (fixed for >= 0.10), so be carefully with that in 0.9.

**Comment by szepeviktor** [comment]
Thank you.

So `GET /`rm -rf /` could destroy servers of my clients?

**Comment by kevin-olbrich** [comment]
This issue is really annoying. I try to provision fail2ban jail.d using a CMDB, based on which packages are installed.
Example: I got a lot of VMs that have apache2 and nginx installed and using the CMDB, the host decides which one is used. In my CMDB I deploy both jails but one will fail on fresh hosts, as the log won't exist.
I can touch the log files but that is just a workaround.

Maybe it would be good idea to add an option in fail2ban, that allows silent fails for jails. Currently fail2ban crashs if something is wrong (which is fine to allow monitoring tools to notify the admin).
With on option, the admin can decide what he wants:
a) Crash as a whole to show something is not working correctly.
b) Keep running without jails that failed and just warn in log.

Currently this is a blocker for me, is there any chance to make this configurable soon?

**Comment by ChuckNorrison** [comment]
want to try install fail2ban manually on ubuntu 20 server... it fails with this

**Comment by szepeviktor** [comment]
Hello Chuck! Welcome to Fail2Ban!

**Comment by ChuckNorrison** [comment]
Solved with systemd in jail.conf. Works great, thanks

**Comment by gnat** [comment]
Still an issue re: https://github.com/fail2ban/fail2ban/issues/2756

Using emptylog as a workaround:
```ini
[jail]
logpath = %(known/logpath)s
          /etc/fail2ban/emptylog
```

**Comment by Jomshanseat** [comment]
Run it on a self-made server, ubuntu server 22.04.04(LTS) and after trying to insert the 403 error message giver of [here](https://www.ctrl.blog/entry/fail2ban-http403.html), the service complains over the lacking log file for the selinux-ssh jail.

Already tried all the options given here, with the error persisting through purges and installing again afterwards. 

Kinda unsure on what to do here.

**Comment by sebres** [comment]
> I run it on a self-made server, ubuntu server 22.04.04(LTS) and after trying to insert the 403 error message giver of [here](https://www.ctrl.blog/entry/fail2ban-http403.html), the service complains over the lacking log file for the selinux-ssh jail.

The mentioned description doesn't speak about `selinux-ssh` jail at all (it is rather about new jail `httpd-forbidden`).

Either check the jail `selinux-ssh` (set proper `logpath` or `backend = systemd` if it is logging to systemd-journal) or in worse case disable this jail if you don't have it.

**Comment by Jomshanseat** [comment]
> The mentioned description doesn't speak about `selinux-ssh` jail at all (it is rather about new jail `httpd-forbidden`).
Ye, I know, personally find it rather weird that that file complains. 
 
> Either check the jail `selinux-ssh` (set proper `logpath` or `backend = systemd` if it is logging to systemd-journal) or in worse case disable this jail if you don't have it.
Checked selinux-ssh.conf and it doesn't seem to have either a `logpath` or `backend` inside. 
Exact error code is `[67789]: ERROR   Failed during configuration: Have not found any log file for selinux-ssh jail`, if that helps

**Comment by sebres** [comment]
> Checked selinux-ssh.conf and it doesn't seem to have either a logpath or backend inside.

Well every local jail-configuration (no matter in `jail.local` or `jail.d/*.conf`) overwrites default configuration `jail.conf`, 
which contains:
https://github.com/fail2ban/fail2ban/blob/8be16f1c1cb23d0a9e193a0a9c77996a7d038cd7/config/jail.conf#L292-L295

The default backend and logpath (or here the value of `auditd_log`) is a matter of maintainer of fail2ban for your distribution.
If they not correct (outdated) for some reason, one needs to overwrite them by oneself (if one enables a jail).
Normally no one jail should be enabled by default, but (who knows) again it may be in some maintainer patches for that distro.

To check what is configured, one can also use:
```bash
# dump config:
fail2ban-client -d
# or pretty dump:
fail2ban-client --dp
```

**Comment by Jomshanseat** [comment]
[Fail2Ban_Dump.txt](https://github.com/fail2ban/fail2ban/files/14578166/Fail2Ban_Dump.txt)
Did that, it actually seems that all of the log files are missing and the selinux jail was just the first to trigger the error.
Is there a way to regenerate the log file(s) or deleting whatever is currently not allowing them to be recreated so the purge+reinstall process can do that?

**Comment by sebres** [comment]
Fail2ban doesn't have currently any possibility to detect which services are active or not and to enable corresponding jails fully automatically.

Don't enable all jails (do it only for jails you need for services you really have).
Don't set `enabled = true` for default section - it'd again enable all jails.
Silencing the errors by creating of empty log-files is wrong way - neither it is good practice, nor it'd really protect everything:
such jails will never find any failure, if service logs to different logpath for some reason (`logpath` is wrong) or service logs to systemd journal but jail monitors log-file yet (`backend` is wrong), but would consume system resources (so the extra load is unnecessary).
More about in https://github.com/fail2ban/fail2ban/wiki/Proper-fail2ban-configuration
This is the way.

**Comment by nick16** [comment]
While waiting for an official solution, I want to share my simple solution for fail2ban to reference the latest jellyfin logs.
I created a cron job to reload fail2ban daily.

To add a cron job (for Ubuntu Server)
`sudo crontab -e`

Then write your cron job
`@daily /usr/bin/fail2ban-client reload`

**Comment by sebres** [comment]
1. you don't need to reload whole fail2ban, it is enough to reload the jail;
2. alternative and probably much simpler way would be to (re)create a link with fixed name to daily log-file, and configure the jail to monitor this linked file instead of some pattern, matched daily logs;
3. or simply switch to journal logging if possible (and then use `backend = systemd`);
