### ISSUE TITLE
Unsupported operand type(s) for +: 'float' and 'str'

### ISSUE THREAD

**Issue by Inglebard** [fail2ban/fail2ban#2241]
### Environment:

- Fail2Ban version (including any possible distribution suffixes): Fail2Ban v0.10.2 (0.10.2-2)
- OS, including release name/version:  Ubuntu 18.04.1
- [x] Fail2Ban installed via OS/distribution mechanisms
- [x] Some customizations were done to the configuration (provide details below is so)

### The issue:

Hi

First of all, it's not an issue with the "vanilla" Fail2ban the issue appear after some changes in the configurations files.

Since Ubuntu 14.04, I use a list from https://greensnow.co/ to ban (permanently and persistently ) IPs.

To achieve that I use a modify configuration file, what we can find easily on google.
I know it's not the best way to achieve that but it works as expected.

```
# Fail2Ban configuration file
#
# Author: Cyril Jaquier
# Modified by Yaroslav Halchenko for multiport banning
#

[INCLUDES]

before = iptables-common.conf

[Definition]

# Option:  actionstart
# Notes.:  command executed once at the start of Fail2Ban.
# Values:  CMD
#
actionstart = <iptables> -N f2b-<name>
              <iptables> -A f2b-<name> -j <returntype>
              <iptables> -I <chain> -p <protocol> -m multiport --dports <port> -j f2b-<name>
              cat /etc/fail2ban/blacklist.conf | while read IP; do iptables -I f2b-<name> 1 -s $IP -j DROP; done

# Option:  actionstop
# Notes.:  command executed once at the end of Fail2Ban
# Values:  CMD
#
actionstop = <iptables> -D <chain> -p <protocol> -m multiport --dports <port> -j f2b-<name>
             <iptables> -F f2b-<name>
             <iptables> -X f2b-<name>

# Option:  actioncheck
# Notes.:  command executed once before each actionban command
# Values:  CMD
#
actioncheck = <iptables> -n -L <chain> | grep -q 'f2b-<name>[ \t]'

# Option:  actionban
# Notes.:  command executed when banning an IP. Take care that the
#          command is executed with Fail2Ban user rights.
# Tags:    See jail.conf(5) man page
# Values:  CMD
#
actionban = <iptables> -I f2b-<name> 1 -s <ip> -j <blocktype>
            echo "<ip>" >> /etc/fail2ban/blacklist.conf

# Option:  actionunban
# Notes.:  command executed when unbanning an IP. Take care that the
#          command is executed with Fail2Ban user rights.
# Tags:    See jail.conf(5) man page
# Values:  CMD
#
actionunban = <iptables> -D f2b-<name> -s <ip> -j <blocktype>

[Init]

timeout = 3600
```

This work great until I upgrade to Ubuntu 18.04.1.
Fail2ban display an "big" error after the startup (Here is a small part of the error line, I hide IPs) : 

```
2018-09-25 14:42:42,418 fail2ban.actions        [7429]: NOTICE  [nginx-dos] Restore Ban w.x.y.z
2018-09-25 14:42:42,423 fail2ban.actions        [7429]: ERROR   Failed to execute ban jail 'nginx-dos' action 'iptables-multiport' info 'ActionInfo({'ip': 'w.x.y.z', 'family': 'inet4', 'ip-rev': 'w.x.y.z.', 'ip-host': 'w-x-y-z.rev.poneytelecom.eu', 'fid': 'w.x.y.z', 'failures': 300, 'time': 1537879084.3232906, 'matches': 'w.x.y.z - - [25/Sep/2018:12:14:29 +0200]  "GET //xmlrpc.php HTTP/1.1" 403 178 "-" "Python-urllib/2.7" Host : domain.fr\nw.x.y.z 
.....
seems to display a full log of nginx
.....
 'ipfailures': 987, 'ipjailfailures': 600})': unsupported operand type(s) for +: 'float' and 'str'
```

Any idea of what's going wrong ?

**Comment by evilplan** [comment]
Wow, that's exactly the issue I came here to post about!

I believe it's related to the fact that you're running a shell command inside a python script (the 'echo' command).

**The first thing to say is: the ban DOES work.** From my understanding, it is just the "echo...." that causes the error - but please check the blacklist.conf file - maybe it still also echoes the IP address to the file. Even when I get the error message, everything works.

You can check if the ban is working by using _iptables -nvL | grep [whatever the IP address is]_ - if the IP is banned it'll be there. You might also have to try ip6tables if it's an ip6 address.

You can also query Fail2Ban directly: _fail2ban-client status [the jail name] | grep [whatever the IP address is]_ (don't use the square brackets - just put the jail name and IP address).

That should tell you if this is the same thing I'm talking about - if the ban works, it's just related to how Python is handling the shell command.

If it's ok, I'd like to add details my own issue here, because I think the solution will be the same. If that is not ok, please let me know and I will delete this :-)

I have a shell script to run when I ban an IP. It's a replacement for sendmail-whois-lines - it does all sorts of nice things to send me really detailed emails.

But I get exactly the same error message. Even if I simply make the shell script say "echo 'hello'", I get the error. 

My sendmail-whois-lines.conf file has this for the ban action:

_actionban = /usr/bin/timeout --kill-after=600 240 /etc/fail2ban/action.d/fail2ban.action "<ip>" "<name>" "<failures>" "<logpath>" "unban" "<bancount>" "<matches>" 2>>/root/fail2ban-script-error_

But even when I changed it to just _actionban = /hello.sh_ and the file hello.sh just contained 

_#!/bin/sh
echo "hello!"_

it returned the same error Inglebard has reported.

That's what makes me think it's exactly the same issue.

**Therefore, I guess the question for both Inglebard and me is: how can we run shell commands/scripts in Fail2Ban actions without generating error messages?**

**Comment by sebres** [comment]
I cannot reproduce both (neither the subject case, nor the test with `hello.sh`) with current upstream 0.10 version.
Either the 0.10.2 had a bug (occurred only in some error case by the action, so that the actual error, that really happens, was not logged and instead of one saw `unsupported operand`). Then it was fixed, because is not reproducible anymore.
Or it may be something else (for example python version related)... 
So which python is used (`fail2ban-python --version`)?

---
In my case (tested with hello.sh with py2.7 as well as py3.5):
  1. error test case (no execute permissions for "/tmp/hello.sh" used in action):
```sh
$ ls -la /tmp/hello.sh
-rw-r--r-- 1 user user 24 Sep 26 17:13 /tmp/hello.sh
$ ?sudo? fail2ban-client set test-ban banip 192.0.2.1
$ ?sudo? fail2ban-client set test-ban unbanip 192.0.2.1
```
results in log:
```
 NOTIC [test-ban] Ban 192.0.2.1
 DEBUG /tmp/hello.sh
 Level 7fc3d243aae0 -- exec: /home/bcadmin/Projects/hello.sh
 ERROR 7fc3d243aae0 -- stderr: '/bin/sh: 1: /tmp/hello.sh: Permission denied'
 ERROR 7fc3d243aae0 -- returned 126
 ERROR Failed to execute ban jail 'test-ban' action 'hello' info 'ActionInfo({'ip': '192.0.2.1', 'fid': <function <lambda> at 0x7fc3d3103488>, 'raw-ticket': <function <lambda> at 0x7fc3d3103938>})': Error banning 192.0.2.1
```
  2. success test case:
```sh
$ chmod +x /tmp/hello.sh
$ ls -la ../hello.sh
-rwxr-xr-x 1 user user 24 Sep 26 17:13 /tmp/hello.sh
$ ?sudo? fail2ban-client set test-ban banip 192.0.2.1
$ ?sudo? fail2ban-client set test-ban unbanip 192.0.2.1
```
results in log:
```
 NOTIC [test-ban] Ban 192.0.2.1
 DEBUG /tmp/hello.sh
 DEBUG 7fc3d243aae0 -- stdout: 'hello!'
 DEBUG 7fc3d243aae0 -- returned successfully 0
```
---
Note that DEBUG messages are vissible only if fail2ban running with DEBUG log-level.

But the actual error looks like (**and I miss this 2 lines in your excerpt**):
```diff
 NOTICE [<jail>] Ban <ip>
-ERROR  <hex> -- stderr: <error-message>
-ERROR  <hex> -- returned <error-code>
 ERROR  Failed to execute ban jail '<jail>' action '<action-name>' info:... : Error banning <ip>
```
And this is very old, so normally it should be the same with any 0.10-th version (also 0.10.2).

Possibly exactly this problem (missing convertion of some float to str in log-output) was fixed in #2171 (together with the encoding things)... No time to check it right now.

**Comment by Inglebard** [comment]
Hi,

@evilplan 
It's difficult to say if it actually ban IPs properly.
Yes, I can see in the iptables the IPs I would like to ban persistently. However, I also notice, this error produce 1 or 2 zombie processes and not handle/delete the rules/jail when I stop fail2ban.

@sebres 
```
$ fail2ban-python --version
Python 3.6.6
```
Tell me if tests/more log can help .

**Comment by evilplan** [comment]
I'm on python 2.7.5, with fail2ban 0.11.0.dev2

I'm going to set up some new tests, to see if it helps us isolate the problem.

**Comment by sebres** [comment]
@Inglebard Another question was also "Do you see the 2 lines (as red marked above)?"

@evilplan is #2171 merged in your used version? 
Or better could you try the latest one from here, whether the issue is then resolved?

**Comment by evilplan** [comment]
Hi - I've just installed the latest version and the issue is still there. I've been seeing some very strange behaviour when I try different tests, but I need to make sure I'm doing reproducible things before I post them here. That might take a day or two, but I'll definitely provide more info ASAP.

**Comment by sebres** [comment]
Good to know, thanks. Then, I'll also try to find the expected constellation...
But if you can easy reproduce this, setting F2B log-level to DEBUG may help vastly, because you'll see the full call-stack after this error in fail2ban.log (so provide it here please).

**Comment by Inglebard** [comment]
> @Inglebard Another question was also "Do you see the 2 lines (as red marked above)?"
> 
> @evilplan is #2171 merged in your used version?
> Or better could you try the latest one from here, whether the issue is then resolved?

I don't see the 2 lines but i have  : 
```
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/fail2ban/server/actions.py", line 401, in __checkBan
    action.ban(aInfo)
  File "/usr/lib/python3/dist-packages/fail2ban/server/action.py", line 430, in ban
    self.start(family)
  File "/usr/lib/python3/dist-packages/fail2ban/server/action.py", line 412, in start
    return self._executeOperation('<actionstart>', 'starting', family=family)
  File "/usr/lib/python3/dist-packages/fail2ban/server/action.py", line 374, in _executeOperation
    res &= self.executeCmd(startCmd, self.timeout)
  File "/usr/lib/python3/dist-packages/fail2ban/server/action.py", line 802, in executeCmd
    return Utils.executeCmd(realCmd, timeout, shell=True, output=False, **kwargs)
  File "/usr/lib/python3/dist-packages/fail2ban/server/utils.py", line 197, in executeCmd
    retcode = Utils.wait_for(_popen_wait_end, timeout, Utils.DEFAULT_SHORTEST_INTERVAL)
  File "/usr/lib/python3/dist-packages/fail2ban/server/utils.py", line 306, in wait_for
    time0 = time.time() + timeout
TypeError: unsupported operand type(s) for +: 'float' and 'str'

```

**Comment by sebres** [comment]
> `time0 = time.time() + timeout`

Yep, that's it - Thanks.
For some reasons, the timeout is not converted to the integer (time) from the string here.
I'll check why, but until not fixed for you, you can simply remove or comment this out:
```ini
[Init]
timeout = 3600
```

**Comment by sebres** [comment]
Fixed in 6067579464f32e81f4810692cf465219ae6b2537.

BTW. Your config looks like an atavism (possibly copied from some obsolete actions where `timeout` was confused with the `bantime`), anyway the value for `timeout` (it is just the max time how long an action command could be executed) is too large (currently 1 hour) - default value is 1 minute (and it should be enough for iptables/file-append). Perhaps it is not enough for your cycled "restore" of ips in `actionstart`, but...
- either you should use `iptables-restore --noflush` for bulk restore instead of single iptable in cycle;
- or use something like recidive jail instead of (or possibly 0.11 with ban-time-increment feature enabled);

Anyway, thank both of you for your contribution.

**Comment by Inglebard** [comment]
Thanks for the fix.

Yeah 1 minutes wasn't enough that why there is this value.

I will check for `iptables-restore`.

Thanks

**Comment by evilplan** [comment]
I just wanted to leave a note for you, @sebres - I had this problem for a long time, and I always assumed it was some error in my Bash script.

But you have resolved it for me, and I want to express my sincere gratitude to you for all the help you give and work you do.

Tony
