### ISSUE TITLE
[BR]: Fail2Ban v1.0.2 treating old Epoc timestamps in log files "as if they just happened"

### ISSUE THREAD

**Issue by wpkc** [fail2ban/fail2ban#3544]
### Environment:

- Fail2Ban version : 1.0.2-2
- OS, including release name/version :  Debian GNU/Linux 12 (bookworm) x86_64
- [x] Fail2Ban installed via OS/distribution mechanisms
- [x] You have not applied any additional foreign patches to the codebase
- [x] Some customizations were done to the configuration (provide details below is so)

### The issue:

I'm not 100% sure, but there may be a regression on the handling of Epoc timestamps, only I don't know how to verify it.  Fail2Ban 1.0.2 is re-banning IPs it already banned every 40 minutes (my default bantime and findtime), but only on data in log files that use an Epoc timestamp.

#### Steps to reproduce

I wrote the filter shown below for Debian Buster/Fail2Ban 0.10.2-2.1, and it worked fine.  Then I bit the bullet and did a Buster => Bullseye => Bookworm upgrade.  Ever since then, this filter re-bans everything that matches in the log files, even if it is older than the findtime setting.  I'm pretty sure the target log files for this filter are the only log files Fail2Ban is monitoring that uses Epoc timestamps.

#### Expected behavior
Should work as before.

#### Observed behavior
Doesn't work as before.  "findtime" doesn't seem to work with log files that begin with Unix Epoc timestamps.

#### Any customizations done to /etc/fail2ban/ configuration

```
# Fail2Ban configuration file
#
# Author: Kazimer Corp
#

[INCLUDES]

# Read common prefixes. If any customizations available -- read them from
# common.local
after = common.conf


[Definition]

_daemon = ninjafirewall-logs

# Option:  failregex
# Notes:   regex to match events marked Critical and High in ninjafirewall log files.
#          fail2ban automatically detects and translates the Epoch timestamp at the
#          start of each log file line even though it is not specified in failregex.
#
#          Samples:
#          [1592563704] [0.01517] [mydomain.com] [#1937399] [1515] [3] [168.61.187.205] [403] [GET] [/index.php] [Unauthorized action] [hex:4745543a712305f6175746f5fab2f67203d2074727565]
#          [1592843376] [0.0003] [mydomain.com] [#2350962] [0] [1] [45.152.182.137] [404] [GET] [/wp-login.php] [Blocked access to the login page] [hex:62612320646574656fca374696f6e20697320656e61626c6564]
#          [1592824252] [0] [mydomain.com] [#7248950] [0] [2] [192.168.0.62] [403] [GET] [/index.php] [User enumeration scan (WP REST API)] [hex:2f2f7abe2d6a7123452f77702f76322f75736572732f]
#          [1592870815] [0] [mydomain.com] [#7392965] [0] [6] [10.0.0.207] [403] [POST] [/wp-login.php] [Logged in user] [hex:736afb61646d696e202861646d696e6973123451746f7229]
#
# Values:  TEXT
#
failregex = \[(?:[\d\.]{1,8})\] \[(?:[\w\.\-]{4,80})\] \[\#(?:\d{5,9})\] \[(?:\d{1,6})\] \[[23]\] \[<HOST>\] \[(?:\d{3})\] \[(?:POST|GET|PUT|PATCH|DELETE)\] \[

# Option:  ignoreregex
# Notes.:  regex to ignore. If this regex matches, the line is ignored.
# Values:  TEXT
#
ignoreregex = <\?php exit; >
```

#### Relevant parts of /var/log/fail2ban.log file:

```
2023-07-22 21:50:02,507 fail2ban.filter         [732]: WARNING [ninjafirewall-logs] Detected a log entry 3w 21h before the current time in operation mode. This looks like a timezone problem. Treating such entries as if they just happened.
2023-07-22 21:50:02,507 fail2ban.filter         [732]: WARNING [ninjafirewall-logs] Please check a jail for a timing issue. Line with odd timestamp: [1688172645] [0] [mysite.com] [#8442766] [0] [6] [67.0.193.131] [403] [POST] [/wp-login.php] [Logged in user] [hex:6d6a1b747042124...
```

#### Relevant lines from monitored log files:

```
[1688172645] [0] [mysite.com] [#8442766] [0] [6] [67.0.193.131] [403] [POST] [/wp-login.php] [Logged in user] [hex:6d6a1b7470421246f773336]
```

**Comment by wpkc** [comment]
I just noticed that...
```
[INCLUDES]
after = common.conf
```
...should probably be...
```
[INCLUDES]
before = common.conf
```

I made that change and should know in 40 minutes if that was the problem.

**Comment by wpkc** [comment]
That seems to have fixed the problem.  I'll leave this here in case it helps anyone else out.

**Comment by wpkc** [comment]
That seems to have fixed the problem. I'll leave this here in case it helps anyone else out.

**Comment by wpkc** [comment]
Sorry... spoke too soon.  This is still a problem.   I just got a load of delayed email notices with IPs being re-banned that had not shown up in several weeks.

**Comment by ann0see** [comment]
I believe I also have this problem. My monitoring system nags that fail2ban has errors:

```
fail2ban.filter         [693]: WARNING [apache-fakegooglebot] Detected a log entry 1m 31s before the current time in operation mode. This looks like a latency problem. Treating such entries as if they just happened.
2023-07-25 14:38:10,072 fail2ban.filter         [693]: WARNING [apache-fakegooglebot] Please check a jail for a timing issue. Line with odd timestamp: ...
```

**Comment by wpkc** [comment]
Yes!  I'm seeing that in my /var/log/fail2ban.log files too, except it is complaining about an entry being 3 weeks, 21 hours _before_ the current time! 
```
2023-07-22 21:50:02,507 fail2ban.filter         [732]: WARNING [ninjafirewall-logs] Detected a log entry 3w 21h before the current time in operation mode. This looks like a timezone problem. Treating such entries as if they just happened.
2023-07-22 21:50:02,507 fail2ban.filter         [732]: WARNING [ninjafirewall-logs] Please check a jail for a timing issue. Line with odd timestamp: [1688172645] [0] [mysite.com] [#8442766] [0] [6] [67.0.193.131] [403] [POST] [/wp-login.php] [Logged in user] [hex:6d6a1b747042124...
```
Looking back through my fail2ban log files, this message only started to show up after the switch from v0.11.2 to v1.0.2.  Even though this is just a warning, and findtime is set to 40 minutes, it is still trying to re-ban every triggered IP address in the month-long log file.

Although I did see another timezone message in the v0.11.2 parts of the log file...
```
2023-07-16 05:50:03,747 fail2ban.filter         [706]: WARNING [ninjafirewall-logs] Simulate NOW in operation since found time has too large deviation None ~ 1689486603.7470052 +/- 60
2023-07-16 05:50:03,747 fail2ban.filter         [706]: WARNING [ninjafirewall-logs] Please check jail has possibly a timezone issue. Line with odd timestamp: <?php exit; ?>
```
But I think this is not a problem.  The log files for the WordPress NinjaFirewall plugin are written to .php files and terminated with a `<?php exit; ?>`  I had tried to add that to the ignoreregex, but fail2ban picks the text up as a timestamp before the ignoreregex can be executed.

**Comment by ann0see** [comment]
I believe that something is wrong with either the application which does the logging or Fail2ban misinterprets timestamps (didn't check that but seems unlikely)

**Comment by sebres** [comment]
Longer thinking about that, I guess it is also important to know how the log rotation happens and whether it can somehow "conflict" with specified `logpath` (e. g. wildcard patterns like `/some/path/*.log`)...
Otherwise I can't really follow how such old entries become recognized as new.

**Comment by wpkc** [comment]
This filter is for the [NinjaFirewall WordPress Plugin](https://nintechnet.com/ninjafirewall/wp-edition/).  

Due to security settings in shared hosting situations, the log files are stored inside the web-root.  Also, the log files are stored as PHP files.  I assume this makes it easy to a) have write access via the web server hosting account, and b) control access with .htaccess.

The log files are stored in WordPress like this...

```
/var/www/vhosts/mywebsite.com/htdocs/wp-content/nfwlog/
|___ .htaccess
|___ firewall_2023-05.php
|___ firewall_2023-06.php
|___ firewall_2023-07.php
```

The log files are not rotated by logrotate. Using logrotate would corrupt the data.  Data is continuously added for an entire month before creating a new file.  There is an upper limit to the size of the log files, and NinjaFirewall will trim the earliest entries when it goes over a given size.  I don't remember the max size, but I can find out for you if it is important.  The plugin user can configure how many months of data are kept, but the default is to keep all data forever.  I previously limited it to 3 months to go easy on Fail2Ban.  After this problem started happening, I set the maximum to one month.

The log file format starts with a `<?php exit; ?>`  followed by the logfile data.  For example...
```
<?php exit; ?>
[1688185757] [0] [mywebsite.com] [#6427151] [0] [2] [138.199.60.185] [403] [GET] [/index.php] [WordPress: Blocked access to the WP REST API] [hex:2f77702d6a736f6e2f6f656d6265642f348349873458743348747470733a2f2f774657466732e636f6d2f]
[1688200792] [0.00265] [mywebsite.com] [#4877801] [0] [6] [54.88.179.33] [200] [GET] [/index.php] [Sanitising user input] [hex:485454505f555345525f4147454e543a2042384729837498237498273498857696e646f773336]
```
I assume that the NinjaFirewall plugin reads the directory, then to display the log data in the user interface each file is read as plain-text, skipping the first line, then formatting the remaining lines for display.  I'm not sure why they chose to use .php files since they could have just as easily blocked direct http access to a .log or .txt file with .htaccess.  But there you have it.

My filter is shown above.  In `jail.local` I configure the log file path as...
```
logpath = /var/www/vhosts/mywebsite.com/htdocs/wp-content/nfwlog/firewall_*.php
```

My observation is that every 40 minutes (my `findtime` and `bantime` setting) fail2ban would go back through all existing firewall_*.php files and re-ban every IP address caught by the filter + maxretry setup.  I can limit the log files to only one month saved.  But toward the end of the month, there is a lot of re-banning activity every 40 minutes.

Can I access the extracted timestamp in my filter?  Is there a way I can re-write my filter so that it skips lines with Epoc timestamps that are less than `currenttime - findtime`?

Thanks for any help or suggestions.

**Comment by sebres** [comment]
> every 40 minutes (my findtime and bantime setting) fail2ban would go back through all existing firewall_*.php files and re-ban every IP address caught by the filter + maxretry setup.

Normally it would not do that at all - the scan from last known position occurs only by restart/reload the jail. So unless such reload would take place (e.g. by cron or some event), fail2ban would continue to monitor the log in operation mode, line by line.
**But** if the rotation of files takes places incorrectly - for example, if all log files shifted by +1 or content of them will be rewritten, so every already processed log file or part of them will be considered as new data - fail2ban will be confused by such kind of rotation.
In this case only one can help - restriction of `logpath` to grep only single not rotated file. See https://github.com/fail2ban/fail2ban/issues/2947#issuecomment-784229259 for similar problem.
Anyway, as already said, normally fail2ban would not scan the file(s) back, if they aren't rewritten and the content of them before last known position isn't changed (the files becomes only appended)... Something seems to be really wrong here, because even after reload fail2ban knows the last position for every file and would not scan before that position. Maybe the files will be rewritten from scratch, so an interim modification event arriving fail2ban confuses it, because in the meantime the file becomes smaller than previously, so fail2ban may think it was rotated and start to scan it from scratch.

>  Is there a way I can re-write my filter so that it skips lines with Epoc timestamps that are less than currenttime - findtime?

No, it's impossible with regex. Also there is no setting at the moment that can be used to achieve that.

**Comment by sebres** [comment]
Anyway if log rotation gets detected (and scan beginning from start of file), fail2ban writing a log entry like:
```
Log rotation detected for /path/to/log
```
Although it'll be logged with level MSG, so one'd need to set it for fail2ban or jail.
Possibly DEBUG or HEAVYDEBUG were also interesting to test, although they are too wordy after all (fail2bans log will be also very large).

**Comment by wpkc** [comment]
Here is the reload with loglevel set to DEBUG...

```
2023-07-31 22:40:22,419 fail2ban.server         [38447]: INFO    Reload jail 'ninjafirewall-logs'
2023-07-31 22:40:22,419 fail2ban.filter         [38447]: DEBUG   Setting usedns = warn for FilterPyinotify(Jail('ninjafirewall-logs'))
2023-07-31 22:40:22,419 fail2ban.server         [38447]: DEBUG     ignoreregex: '\\<\\?php exit'
2023-07-31 22:40:22,419 fail2ban.server         [38447]: DEBUG     failregex: '\\[(?:[\\d\\.]{1,8})\\] \\[(?:[\\w\\.\\-]{4,80})\\] \\[\\#(?:\\d{5,9})\\] \\[(?:\\d{1,6})\\] \\[[23]\\] \\[<HOST>\\] \\[(?:\\d{3})\\] \\['
2023-07-31 22:40:22,419 fail2ban.filter         [38447]: INFO      maxRetry: 2
2023-07-31 22:40:22,419 fail2ban.filter         [38447]: INFO      findtime: 2400
2023-07-31 22:40:22,419 fail2ban.actions        [38447]: INFO      banTime: 2400
2023-07-31 22:40:22,419 fail2ban.filter         [38447]: DEBUG     Add '127.0.0.0/8' to ignore list ('127.0.0.1/8')
2023-07-31 22:40:22,420 fail2ban.filter         [38447]: DEBUG     Add '::1' to ignore list ('::1/128')
2023-07-31 22:40:22,420 fail2ban.filter         [38447]: DEBUG     Add '4.255.208.59' to ignore list ('4.255.208.59')
2023-07-31 22:40:22,420 fail2ban.filter         [38447]: DEBUG     Add '173.245.48.0/20' to ignore list ('173.245.48.0/20')
2023-07-31 22:40:22,420 fail2ban.filter         [38447]: DEBUG     Add '103.21.244.0/22' to ignore list ('103.21.244.0/22')
2023-07-31 22:40:22,420 fail2ban.filter         [38447]: DEBUG     Add '103.22.200.0/22' to ignore list ('103.22.200.0/22')
2023-07-31 22:40:22,420 fail2ban.filter         [38447]: DEBUG     Add '103.31.4.0/22' to ignore list ('103.31.4.0/22')
2023-07-31 22:40:22,420 fail2ban.filter         [38447]: DEBUG     Add '141.101.64.0/18' to ignore list ('141.101.64.0/18')
2023-07-31 22:40:22,420 fail2ban.filter         [38447]: DEBUG     Add '108.162.192.0/18' to ignore list ('108.162.192.0/18')
2023-07-31 22:40:22,420 fail2ban.filter         [38447]: DEBUG     Add '190.93.240.0/20' to ignore list ('190.93.240.0/20')
2023-07-31 22:40:22,420 fail2ban.filter         [38447]: DEBUG     Add '188.114.96.0/20' to ignore list ('188.114.96.0/20')
2023-07-31 22:40:22,420 fail2ban.filter         [38447]: DEBUG     Add '197.234.240.0/22' to ignore list ('197.234.240.0/22')
2023-07-31 22:40:22,420 fail2ban.filter         [38447]: DEBUG     Add '198.41.128.0/17' to ignore list ('198.41.128.0/17')
2023-07-31 22:40:22,421 fail2ban.filter         [38447]: DEBUG     Add '162.158.0.0/15' to ignore list ('162.158.0.0/15')
2023-07-31 22:40:22,421 fail2ban.filter         [38447]: DEBUG     Add '104.16.0.0/13' to ignore list ('104.16.0.0/13')
2023-07-31 22:40:22,421 fail2ban.filter         [38447]: DEBUG     Add '104.24.0.0/14' to ignore list ('104.24.0.0/14')
2023-07-31 22:40:22,421 fail2ban.filter         [38447]: DEBUG     Add '172.64.0.0/13' to ignore list ('172.64.0.0/13')
2023-07-31 22:40:22,421 fail2ban.filter         [38447]: DEBUG     Add '131.0.72.0/22' to ignore list ('131.0.72.0/22')
2023-07-31 22:40:22,421 fail2ban.filter         [38447]: DEBUG     Add '2400:cb00::/32' to ignore list ('2400:cb00::/32')
2023-07-31 22:40:22,421 fail2ban.filter         [38447]: DEBUG     Add '2606:4700::/32' to ignore list ('2606:4700::/32')
2023-07-31 22:40:22,421 fail2ban.filter         [38447]: DEBUG     Add '2803:f800::/32' to ignore list ('2803:f800::/32')
2023-07-31 22:40:22,421 fail2ban.filter         [38447]: DEBUG     Add '2405:b500::/32' to ignore list ('2405:b500::/32')
2023-07-31 22:40:22,421 fail2ban.filter         [38447]: DEBUG     Add '2405:8100::/32' to ignore list ('2405:8100::/32')
2023-07-31 22:40:22,421 fail2ban.filter         [38447]: DEBUG     Add '2a06:98c0::/29' to ignore list ('2a06:98c0::/29')
2023-07-31 22:40:22,421 fail2ban.filter         [38447]: DEBUG     Add '2c0f:f248::/32' to ignore list ('2c0f:f248::/32')
2023-07-31 22:40:22,421 fail2ban.filter         [38447]: INFO      encoding: UTF-8
2023-07-31 22:40:22,421 fail2ban.CommandAction  [38447]: DEBUG     Set actionstart = "{ <iptables> -C f2b-ninjafirewall-logs -j RETURN >/dev/null 2>&1; } || { <iptables> -N f2b-ninjafirewall-logs || true; <iptables> -A f2b-ninjafirewall-logs -j RETURN; }\nfor proto in $(echo 'tcp' | sed 's/,/ /g'); do\n{ <iptables> -C INPUT -p $proto -m multiport --dports http,https -j f2b-ninjafirewall-logs >/dev/null 2>&1; } || { <iptables> -I INPUT -p $proto -m multiport --dports http,https -j f2b-ninjafirewall-logs; }\ndone"
2023-07-31 22:40:22,422 fail2ban.CommandAction  [38447]: DEBUG     Set actionstop = "for proto in $(echo 'tcp' | sed 's/,/ /g'); do\n<iptables> -D INPUT -p $proto -m multiport --dports http,https -j f2b-ninjafirewall-logs\ndone\n<iptables> -F f2b-ninjafirewall-logs\n<iptables> -X f2b-ninjafirewall-logs"
2023-07-31 22:40:22,422 fail2ban.CommandAction  [38447]: DEBUG     Set actionflush = '<iptables> -F f2b-ninjafirewall-logs'
2023-07-31 22:40:22,422 fail2ban.CommandAction  [38447]: DEBUG     Set actioncheck = "for proto in $(echo 'tcp' | sed 's/,/ /g'); do\n<iptables> -C INPUT -p $proto -m multiport --dports http,https -j f2b-ninjafirewall-logs\ndone"
2023-07-31 22:40:22,422 fail2ban.CommandAction  [38447]: DEBUG     Set actionban = '<iptables> -I f2b-ninjafirewall-logs 1 -s <ip> -j <blocktype>'
2023-07-31 22:40:22,422 fail2ban.CommandAction  [38447]: DEBUG     Set actionunban = '<iptables> -D f2b-ninjafirewall-logs -s <ip> -j <blocktype>'
2023-07-31 22:40:22,422 fail2ban.CommandAction  [38447]: DEBUG     Set name = 'ninjafirewall-logs'
2023-07-31 22:40:22,422 fail2ban.CommandAction  [38447]: DEBUG     Set port = 'http,https'
2023-07-31 22:40:22,422 fail2ban.CommandAction  [38447]: DEBUG     Set protocol = 'tcp'
2023-07-31 22:40:22,422 fail2ban.CommandAction  [38447]: DEBUG     Set chain = 'INPUT'
2023-07-31 22:40:22,422 fail2ban.CommandAction  [38447]: DEBUG     Set actname = 'iptables-multiport'
2023-07-31 22:40:22,422 fail2ban.CommandAction  [38447]: DEBUG     Set blocktype = 'REJECT --reject-with icmp-port-unreachable'
2023-07-31 22:40:22,422 fail2ban.CommandAction  [38447]: DEBUG     Set returntype = 'RETURN'
2023-07-31 22:40:22,422 fail2ban.CommandAction  [38447]: DEBUG     Set lockingopt = '-w'
2023-07-31 22:40:22,422 fail2ban.CommandAction  [38447]: DEBUG     Set iptables = 'iptables <lockingopt>'
2023-07-31 22:40:22,422 fail2ban.CommandAction  [38447]: DEBUG     Set blocktype?family=inet6 = 'REJECT --reject-with icmp6-port-unreachable'
2023-07-31 22:40:22,422 fail2ban.CommandAction  [38447]: DEBUG     Set iptables?family=inet6 = 'ip6tables <lockingopt>'
2023-07-31 22:40:22,422 fail2ban.CommandAction  [38447]: DEBUG     Set actionstart = ''
2023-07-31 22:40:22,422 fail2ban.CommandAction  [38447]: DEBUG     Set actionstop = ''
2023-07-31 22:40:22,422 fail2ban.CommandAction  [38447]: DEBUG     Set actioncheck = ''
2023-07-31 22:40:22,422 fail2ban.CommandAction  [38447]: DEBUG     Set actionban = 'curl -s -X POST https://api.cloudflare.com/client/v4/user/firewall/access_rules/rules \\\n-H "Authorization: Bearer ___RemovedForPrivacy___" -H "Content-Type: application/json" \\\n--data \'{"mode":"block","configuration":{"target":"ip","value":"<ip>"},"notes":"Banned by Fail2Ban"}\''
2023-07-31 22:40:22,423 fail2ban.CommandAction  [38447]: DEBUG     Set actionunban = 'curl -s -X GET -H "Authorization: Bearer ___RemovedForPrivacy___" -H "Content-Type: application/json" \\\n"https://api.cloudflare.com/client/v4/user/firewall/access_rules/rules?page=1&per_page=1&mode=block&configuration.target=ip&configuration.value=<ip>&match=all&order=configuration.value&direction=desc" | \\\npython -c "import sys, json; print json.load(sys.stdin)[\'result\'][0][\'id\'];" | \\\nxargs -I@@ curl -s -X DELETE -H "Authorization: Bearer ___RemovedForPrivacy___" -H "Content-Type: application/json" https://api.cloudflare.com/client/v4/user/firewall/access_rules/rules/@@'
2023-07-31 22:40:22,423 fail2ban.CommandAction  [38447]: DEBUG     Set cfkey = '___RemovedForPrivacy___'
2023-07-31 22:40:22,423 fail2ban.CommandAction  [38447]: DEBUG     Set name = 'ninjafirewall-logs'
2023-07-31 22:40:22,423 fail2ban.CommandAction  [38447]: DEBUG     Set actname = 'cloudflare-restv4-bearer-token'
...
2023-07-31 22:40:22,423 fail2ban.server         [38447]: INFO    Jail 'ninjafirewall-logs' reloaded
2023-07-31 22:40:22,425 fail2ban.server         [38447]: INFO    Reload finished.
```

**Comment by wpkc** [comment]
The detection starts off like this...
```
2023-07-31 22:50:03,008 fail2ban.filter         [38447]: INFO    [ninjafirewall-logs] Found 138.199.60.185 - 2023-07-31 22:50:02
2023-07-31 22:50:03,009 fail2ban.filterpyinotify[38447]: DEBUG   Event queue size: 16
2023-07-31 22:50:03,009 fail2ban.failmanager    [38447]: DEBUG   Total # of detected failures: 2. Current failures from 2 IPs (IP:count): 134.209.109.240:1, 138.199.60.185:1
2023-07-31 22:50:03,009 fail2ban.filter         [38447]: DEBUG   Processing line with time:1690843803.0096865 and ip:206.189.95.50
2023-07-31 22:50:03,009 fail2ban.filter         [38447]: INFO    [ninjafirewall-logs] Found 206.189.95.50 - 2023-07-31 22:50:03
2023-07-31 22:50:03,009 fail2ban.failmanager    [38447]: DEBUG   Total # of detected failures: 3. Current failures from 3 IPs (IP:count): 134.209.109.240:1, 138.199.60.185:1, 206.189.95.50:1
2023-07-31 22:50:03,010 fail2ban.filter         [38447]: DEBUG   Processing line with time:1690843803.0100749 and ip:34.87.140.147
2023-07-31 22:50:03,010 fail2ban.filter         [38447]: INFO    [ninjafirewall-logs] Found 34.87.140.147 - 2023-07-31 22:50:03
2023-07-31 22:50:03,009 fail2ban.filterpyinotify[38447]: DEBUG   <_RawEvent cookie=0 mask=0x2 name='' wd=2 >
2023-07-31 22:50:03,010 fail2ban.failmanager    [38447]: DEBUG   Total # of detected failures: 4. Current failures from 4 IPs (IP:count): 134.209.109.240:1, 138.199.60.185:1, 206.189.95.50:1, 34.87.140.147:1
2023-07-31 22:50:03,010 fail2ban.filter         [38447]: DEBUG   Processing line with time:1690843803.010796 and ip:34.87.140.147
2023-07-31 22:50:03,011 fail2ban.filter         [38447]: INFO    [ninjafirewall-logs] Found 34.87.140.147 - 2023-07-31 22:50:03
2023-07-31 22:50:03,011 fail2ban.failmanager    [38447]: DEBUG   Total # of detected failures: 5. Current failures from 4 IPs (IP:count): 134.209.109.240:1, 138.199.60.185:1, 206.189.95.50:1, 34.87.140.147:2
2023-07-31 22:50:03,011 fail2ban.filterpyinotify[38447]: DEBUG   Event queue size: 16
2023-07-31 22:50:03,012 fail2ban.filter         [38447]: DEBUG   Processing line with time:1690843803.0123851 and ip:146.70.192.156
```
Then seems to finish detection like this...
```
2023-07-31 22:50:03,237 fail2ban.filter         [38447]: INFO    [ninjafirewall-logs] Found 192.248.144.4 - 2023-07-31 22:50:03
2023-07-31 22:50:03,238 fail2ban.failmanager    [38447]: DEBUG   Total # of detected failures: 148. Current failures from 64 IPs (IP:count): 138.199.60.185:1, 206.189.95.50:1, 103.216.223.206:1, 178.128.228.237:1, 35.239.114.146:1, 146.70.205.86:1, 138.199.60.181:1, 146.70.205.156:1, 195.140.213.219:1, 34.106.204.242:1, 34.102.74.16:1, 138.199.60.171:1, 195.140.213.240:1, 146.190.90.147:1, 178.239.163.108:1, 67.205.152.112:1, 146.190.98.164:1, 217.146.82.84:1, 185.44.76.187:1, 37.19.205.185:1, 178.128.22.139:1, 138.199.29.131:1, 116.213.36.106:1, 37.19.205.183:1, 35.240.255.226:1, 34.94.141.245:1, 178.128.219.172:1, 139.59.240.67:1, 138.199.29.201:1, 185.44.76.189:1, 146.190.94.97:1, 206.189.95.31:1, 178.239.163.100:1, 109.123.232.250:1, 138.199.29.163:1, 178.238.10.51:1, 34.106.238.159:1, 217.146.83.108:1, 138.199.29.246:1, 139.59.116.201:1, 213.166.86.115:1, 217.146.83.104:1, 198.251.78.62:1, 82.223.54.25:1, 185.245.82.35:1, 165.22.240.105:1, 34.106.251.197:1, 185.44.77.63:1, 178.238.10.195:1, 178.128.82.94:1, 67.205.60.164:1, 38.242.196.129:1, 74.208.18.119:1, 2607:ff28:800f:3301::2fc1:1, 179.127.29.178:1, 88.85.111.67:1, 138.199.29.136:1, 185.44.77.49:1, 138.199.29.243:1, 194.62.19.14:1, 185.44.77.53:1, 69.163.199.44:1, 77.68.112.83:1, 192.248.144.4:1
2023-07-31 22:50:03,238 fail2ban.filterpyinotify[38447]: DEBUG   Event queue size: 16
2023-07-31 22:50:03,238 fail2ban.filter         [38447]: DEBUG   Processing line with time:1690843803.238389 and ip:134.209.109.240
2023-07-31 22:50:03,238 fail2ban.filterpyinotify[38447]: DEBUG   <_RawEvent cookie=0 mask=0x2 name='' wd=2 >
2023-07-31 22:50:03,238 fail2ban.filter         [38447]: INFO    [ninjafirewall-logs] Found 134.209.109.240 - 2023-07-31 22:50:03
2023-07-31 22:50:03,240 fail2ban.failmanager    [38447]: DEBUG   Total # of detected failures: 149. Current failures from 65 IPs (IP:count): 138.199.60.185:1, 206.189.95.50:1, 103.216.223.206:1, 178.128.228.237:1, 35.239.114.146:1, 146.70.205.86:1, 138.199.60.181:1, 146.70.205.156:1, 195.140.213.219:1, 34.106.204.242:1, 34.102.74.16:1, 138.199.60.171:1, 195.140.213.240:1, 146.190.90.147:1, 178.239.163.108:1, 67.205.152.112:1, 146.190.98.164:1, 217.146.82.84:1, 185.44.76.187:1, 37.19.205.185:1, 178.128.22.139:1, 138.199.29.131:1, 116.213.36.106:1, 37.19.205.183:1, 35.240.255.226:1, 34.94.141.245:1, 178.128.219.172:1, 139.59.240.67:1, 138.199.29.201:1, 185.44.76.189:1, 146.190.94.97:1, 206.189.95.31:1, 178.239.163.100:1, 109.123.232.250:1, 138.199.29.163:1, 178.238.10.51:1, 34.106.238.159:1, 217.146.83.108:1, 138.199.29.246:1, 139.59.116.201:1, 213.166.86.115:1, 217.146.83.104:1, 198.251.78.62:1, 82.223.54.25:1, 185.245.82.35:1, 165.22.240.105:1, 34.106.251.197:1, 185.44.77.63:1, 178.238.10.195:1, 178.128.82.94:1, 67.205.60.164:1, 38.242.196.129:1, 74.208.18.119:1, 2607:ff28:800f:3301::2fc1:1, 179.127.29.178:1, 88.85.111.67:1, 138.199.29.136:1, 185.44.77.49:1, 138.199.29.243:1, 194.62.19.14:1, 185.44.77.53:1, 69.163.199.44:1, 77.68.112.83:1, 192.248.144.4:1, 134.209.109.240:1
```

Then it seems to go through the IPs found, trying to ban them in `iptables` and on `CloudFlare`.  But I'm seeing `firewallaccessrules.api.duplicate_of_existing` error messages coming back from CloudFlare since they were re-banned before their bans expired...

```
2023-07-31 22:50:09,174 fail2ban.utils          [38447]: DEBUG   7f8cee9be870 -- stdout: '{'
2023-07-31 22:50:09,174 fail2ban.filterpyinotify[38447]: DEBUG   <_RawEvent cookie=0 mask=0x2 name='' wd=2 >
2023-07-31 22:50:09,174 fail2ban.utils          [38447]: DEBUG   7f8cee9be870 -- stdout: '  "result": null,'
2023-07-31 22:50:09,175 fail2ban.utils          [38447]: DEBUG   7f8cee9be870 -- stdout: '  "success": false,'
2023-07-31 22:50:09,175 fail2ban.utils          [38447]: DEBUG   7f8cee9be870 -- stdout: '  "errors": ['
2023-07-31 22:50:09,175 fail2ban.filterpyinotify[38447]: DEBUG   Event queue size: 16
2023-07-31 22:50:09,175 fail2ban.utils          [38447]: DEBUG   7f8cee9be870 -- stdout: '    {'
2023-07-31 22:50:09,175 fail2ban.filterpyinotify[38447]: DEBUG   <_RawEvent cookie=0 mask=0x2 name='' wd=2 >
2023-07-31 22:50:09,176 fail2ban.utils          [38447]: DEBUG   7f8cee9be870 -- stdout: '      "code": 10009,'
2023-07-31 22:50:09,176 fail2ban.utils          [38447]: DEBUG   7f8cee9be870 -- stdout: '      "message": "firewallaccessrules.api.duplicate_of_existing"'
2023-07-31 22:50:09,176 fail2ban.utils          [38447]: DEBUG   7f8cee9be870 -- stdout: '    }'
2023-07-31 22:50:09,176 fail2ban.filterpyinotify[38447]: DEBUG   Event queue size: 16
2023-07-31 22:50:09,177 fail2ban.utils          [38447]: DEBUG   7f8cee9be870 -- stdout: '  ],'
2023-07-31 22:50:09,177 fail2ban.filterpyinotify[38447]: DEBUG   <_RawEvent cookie=0 mask=0x2 name='' wd=2 >
2023-07-31 22:50:09,177 fail2ban.utils          [38447]: DEBUG   7f8cee9be870 -- stdout: '  "messages": []'
2023-07-31 22:50:09,177 fail2ban.utils          [38447]: DEBUG   7f8cee9be870 -- stdout: '}'
2023-07-31 22:50:09,178 fail2ban.filterpyinotify[38447]: DEBUG   Event queue size: 16
2023-07-31 22:50:09,178 fail2ban.filterpyinotify[38447]: DEBUG   <_RawEvent cookie=0 mask=0x2 name='' wd=2 >
2023-07-31 22:50:09,178 fail2ban.utils          [38447]: DEBUG   7f8cee9be870 -- returned successfully 0
2023-07-31 22:50:09,178 fail2ban.actions        [38447]: DEBUG   Banned 9 / 38, 9 ticket(s) in 'ninjafirewall-logs'
2023-07-31 22:50:09,179 fail2ban.actions        [38447]: NOTICE  [ninjafirewall-logs] Ban 217.146.82.84
2023-07-31 22:50:09,179 fail2ban.filter         [38447]: DEBUG   Processing line with time:1690843809.0 and ip:217.146.82.84
2023-07-31 22:50:09,179 fail2ban.observer       [38447]: DEBUG   [ninjafirewall-logs] Observer: ban found 217.146.82.84, 2400
2023-07-31 22:50:09,180 fail2ban.filter         [38447]: INFO    [recidive] Found 217.146.82.84 - 2023-07-31 22:50:09
2023-07-31 22:50:09,185 fail2ban.failmanager    [38447]: DEBUG   Total # of detected failures: 10. Current failures from 10 IPs (IP:count): 34.87.140.147:1, 146.70.192.156:1, 89.187.163.218:1, 188.166.183.31:1, 178.128.107.141:1, 178.128.111.149:1, 138.199.60.171:1, 206.189.95.31:1, 167.99.69.109:1, 217.146.82.84:1

```

But Fail2Ban was just restarted, so I guess none of this is all that helpful.  I'll have to wait and see if anything interesting shows up after 40 minutes.

**Comment by wpkc** [comment]
I got about 2GB of log data.  I tried to grep "ticket" and "anned" with some context lines.  One interesting thing I saw was a python error in an unban action...
```
2023-07-31 23:30:18,982 fail2ban.filterpyinotify[38447]: DEBUG   <_RawEvent cookie=0 mask=0x2 name='' wd=2 >
2023-07-31 23:30:18,983 fail2ban.filterpyinotify[38447]: DEBUG   Event queue size: 16
2023-07-31 23:30:18,983 fail2ban.utils          [38447]: DEBUG   7f8cd8002b30 -- stderr: '  File "<string>", line 1'
2023-07-31 23:30:18,983 fail2ban.filterpyinotify[38447]: DEBUG   <_RawEvent cookie=0 mask=0x2 name='' wd=2 >
2023-07-31 23:30:18,983 fail2ban.utils          [38447]: DEBUG   7f8cd8002b30 -- stderr: "    import sys, json; print json.load(sys.stdin)['result'][0]['id'];"
2023-07-31 23:30:18,984 fail2ban.utils          [38447]: DEBUG   7f8cd8002b30 -- stderr: '                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^'
2023-07-31 23:30:18,984 fail2ban.utils          [38447]: DEBUG   7f8cd8002b30 -- stderr: "SyntaxError: Missing parentheses in call to 'print'. Did you mean print(...)?"
2023-07-31 23:30:18,984 fail2ban.filterpyinotify[38447]: DEBUG   Event queue size: 16
2023-07-31 23:30:18,984 fail2ban.utils          [38447]: DEBUG   7f8cd8002b30 -- returned successfully 0
2023-07-31 23:30:18,985 fail2ban.filterpyinotify[38447]: DEBUG   <_RawEvent cookie=0 mask=0x2 name='' wd=2 >
2023-07-31 23:30:18,985 fail2ban.actions        [38447]: DEBUG   Unbanned 11, 0 ticket(s) in 'ninjafirewall-logs'
```

I fixed the syntax error and reloaded.  But I don't think that is the cause of the problem since that has to do with an unban action.

**Comment by sebres** [comment]
> I tried to grep "ticket" and "anned" with some context lines.

Didn't you try to grep for "rotation" (e. g. to check where you got the case "Log rotation detected")?

I still assume that the content of files get changed (rewritten). Fail2ban is basically suitable to monitor files or journals growing in append mode only (at least currently implemented backends).

**Comment by wpkc** [comment]
Unfortunately, now that we are in August, my July log file was deleted and a new August file was created.  So I will have to wait for some NinjaFirewall to log more hacking activity before I can do any more experiments.

Grep-ing for "rotation" in the 2GB file, or more precisely "nfw" (the log file directory), I found this...
```
2023-07-31 22:50:02,960 fail2ban.filter         [38447]: MSG     Log rotation detected for /var/www/vhosts/mysite.com/htdoc/wp-content/nfwlog/firewall_2023-07.php, reason: (25373, 286177, 134775, 134775, 'f097e27fc61298b3775739dcc60d0cf398fc5919', 'f097e27fc61298b3775739dcc60d0cf398fc5919')
```
That happened 30 and 50 minutes after the hour is when I have been seeing the re-bans.  So it does seem to be happening at the same time that a log rotation is detected.

From what you are saying, for NinjaFirewall files, it might work up until the point that NinjaFirewall starts trimming the start of the log file due to their self-imposed log file size limitation.

Unfortunately, NinjaFirewall does not offer a way to hook into their logging code.  So I am limited to writing a cron script that copies new events into a proper log file, then monitor that.  That's less than ideal since it means increasing the reaction time to any hacking activity.

**Comment by sebres** [comment]
> `... reason: (25373, 286177, 134775, 134775, 'f097e27fc61298b3775739dcc60d0cf398fc5919', 'f097e27fc61298b3775739dcc60d0cf398fc5919')`

Related to https://github.com/fail2ban/fail2ban/blob/3e6a60f9407596586fe39fa54fd63818c0972b7b/fail2ban/server/filter.py#L1407-L1408

it means that the file is now shorter than read last time: 25K instead of 286K (last known position)... since hash and ino are still the same, it looks like the file will be either really rewritten from scratch or it got truncated for some reason (why should it?).
Anyway from that point fail2ban will consider all entries in this file as new.

I don't know how one can help here. One can surely make "simulate now in operation mode" optional, but it'd be a dirty workaround either... because this is really unexpected situation and normally such a rewrite causing rescan must be avoided outside of fail2ban. No one service writes logs in this way - it is a nonsense.
You could also patch fail2ban to restore previous behavior, e. g. in https://github.com/fail2ban/fail2ban/blob/3e6a60f9407596586fe39fa54fd63818c0972b7b/fail2ban/server/filter.py#L668
```diff
-			if self.inOperation:
+			if False:
```
(just I'd not recommend that for several reasons).
Again, better would be to fix it on side of app writing that "logs".

An alternative could be some different backend, just I can't devise a plan for such backend for correct behavior (if it is even possible without some interim buffer).

>  So I am limited to writing a cron script that copies new events into a proper log file.

Well, one can write a script using `inotifywait` or `python` with `pyinotify` to recognize changes on directory and do... 
Well what should it do? If a file gets rewritten, it is hardly possible to recognize when exactly the other side is ready with that.
Maybe one'd be able to link a current file (if it always get new name), so the algorithm will look like:
```
  if inotify detects new file creation in /path/.../nfwlog/:
    and filename matches firewall_\d{4}-\d{2}\.php:
      ln -fT "$filepath" "/path/firewall.log"
```
Or if it is always the last name somehow like:
```
   ln -fT "$(ls "/path/.../nfwlog/firewall_*.php" | sort -dr | head -n 1)" "/path/firewall.log"
```
... and then configure fail2bans jail to monitor `/path/firewall.log` only.

But if it is really truncate the file from begin... Hmm, then I have no idea excepting some interim buffer (like sql table) to validate every entry against that and ignore already known entries. 
As already said, better would be to avoid such a truncation on the other side.

**Comment by wpkc** [comment]
Thanks @sebres for all your efforts.  You've given me some interesting ideas to experiment with.

My ninjafirewall-logs filter is a bit of a hack to begin with.  The devs that make it are unlikely to change the logging method because they already have a non-free version of their plugin that sends copies of the same log events to syslog.  My filter was an attempt to use the free version's logging.

I'll post later if I come up with any clean solutions.
